### ISSUE TITLE
twitter handle isn't a link

### ISSUE THREAD

**Issue by sneak** [rkd2/rkd2.github.io#1]

**Comment by rkd2** [comment]
Made it a link, thanks

**Comment by sneak** [comment]
> On Jun 22, 2015, at 10:39 PM, rkd2 notifications@github.com wrote:
> 
> Made it a link, thanks
> 
> —
> Reply to this email directly or view it on GitHub.

if you put something like “Fixes #1” in the commit message, it will auto-close issues.
